// <auto-generated />
using System;
using HammamAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HammamAPI.Infrastructure.Migrations
{
    [DbContext(typeof(HammamDbContext))]
    [Migration("20260202123919_AddPasswordClairToEmploye")]
    partial class AddPasswordClairToEmploye
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HammamAPI.Domain.Entities.Employe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("FR")
                        .HasColumnName("langue");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordClair")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("HammamId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("employe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Actif = true,
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 393, DateTimeKind.Utc).AddTicks(1182),
                            HammamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Langue = "FR",
                            Nom = "Administrateur",
                            PasswordHash = "$2a$11$H2Vd5ReuNWLeRDPkjRyEJuLEDTF02/Nb/aaTm4he.En.xn.3KHPda",
                            Prenom = "System",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Hammam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("adresse");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("hammam", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Actif = true,
                            Adresse = "123 Rue Principale, Casablanca",
                            Code = "HAM001",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(4952),
                            Nom = "Hammam Centre"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Actif = true,
                            Adresse = "45 Boulevard Anfa, Casablanca",
                            Code = "HAM002",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(4969),
                            Nom = "Hammam Anfa"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Actif = true,
                            Adresse = "78 Rue Maarif, Casablanca",
                            Code = "HAM003",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(4971),
                            Nom = "Hammam Maarif"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Actif = true,
                            Adresse = "12 Avenue Hassan II, Casablanca",
                            Code = "HAM004",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(4973),
                            Nom = "Hammam Hay Mohammadi"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Actif = true,
                            Adresse = "90 Derb Sultan, Casablanca",
                            Code = "HAM005",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(4978),
                            Nom = "Hammam Derb Sultan"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Actif = false,
                            Adresse = "34 Quartier Sidi Moumen, Casablanca",
                            Code = "HAM006",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(4993),
                            Nom = "Hammam Sidi Moumen"
                        });
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employe_id");

                    b.Property<Guid>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sync_status");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<Guid>("TypeTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeId");

                    b.HasIndex("HammamId");

                    b.HasIndex("TypeTicketId");

                    b.HasIndex("EmployeId", "CreatedAt");

                    b.HasIndex("HammamId", "CreatedAt");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.TypeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("couleur");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User")
                        .HasColumnName("icone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.HasIndex("HammamId");

                    b.ToTable("type_ticket", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            Actif = true,
                            Couleur = "#3B82F6",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(5358),
                            Icone = "User",
                            Nom = "HOMME",
                            Ordre = 1,
                            Prix = 15.00m
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2222-2222-2222-222222222222"),
                            Actif = true,
                            Couleur = "#EC4899",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(5364),
                            Icone = "UserCheck",
                            Nom = "FEMME",
                            Ordre = 2,
                            Prix = 15.00m
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3333-3333-3333-333333333333"),
                            Actif = true,
                            Couleur = "#10B981",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(5368),
                            Icone = "Baby",
                            Nom = "ENFANT",
                            Ordre = 3,
                            Prix = 10.00m
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4444-4444-4444-444444444444"),
                            Actif = true,
                            Couleur = "#06B6D4",
                            CreatedAt = new DateTime(2026, 2, 2, 12, 39, 19, 269, DateTimeKind.Utc).AddTicks(5377),
                            Icone = "Droplets",
                            Nom = "DOUCHE",
                            Ordre = 4,
                            Prix = 8.00m
                        });
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Employe", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany("Employes")
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hammam");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Employe", "Employe")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany("Tickets")
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HammamAPI.Domain.Entities.TypeTicket", "TypeTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("TypeTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Hammam");

                    b.Navigation("TypeTicket");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.TypeTicket", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany("TypeTickets")
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Hammam");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Employe", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Hammam", b =>
                {
                    b.Navigation("Employes");

                    b.Navigation("Tickets");

                    b.Navigation("TypeTickets");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.TypeTicket", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
