// <auto-generated />
using System;
using HammamAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HammamAPI.Infrastructure.Migrations
{
    [DbContext(typeof(HammamDbContext))]
    partial class HammamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HammamAPI.Domain.Entities.Employe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("FR")
                        .HasColumnName("langue");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordClair")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("HammamId");

                    b.HasIndex("Username");

                    b.ToTable("employe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Actif = true,
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 566, DateTimeKind.Utc).AddTicks(5430),
                            HammamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Icone = "User1",
                            Langue = "FR",
                            Nom = "Administrateur",
                            PasswordHash = "$2a$11$vvAB/wgZJCbcM1q7AommdumSxE6NVsGFsgfNGYWSg21RH3zlDkRgq",
                            Prenom = "System",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Hammam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("adresse");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("NomArabe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrefixeTicket")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("hammam", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Actif = true,
                            Adresse = "123 Rue Principale, Casablanca",
                            Code = "HAM001",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9109),
                            Nom = "Hammam Centre",
                            NomArabe = "",
                            PrefixeTicket = 100000
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Actif = true,
                            Adresse = "45 Boulevard Anfa, Casablanca",
                            Code = "HAM002",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9113),
                            Nom = "Hammam Anfa",
                            NomArabe = "",
                            PrefixeTicket = 100000
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Actif = true,
                            Adresse = "78 Rue Maarif, Casablanca",
                            Code = "HAM003",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9116),
                            Nom = "Hammam Maarif",
                            NomArabe = "",
                            PrefixeTicket = 100000
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Actif = true,
                            Adresse = "12 Avenue Hassan II, Casablanca",
                            Code = "HAM004",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9120),
                            Nom = "Hammam Hay Mohammadi",
                            NomArabe = "",
                            PrefixeTicket = 100000
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Actif = true,
                            Adresse = "90 Derb Sultan, Casablanca",
                            Code = "HAM005",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9122),
                            Nom = "Hammam Derb Sultan",
                            NomArabe = "",
                            PrefixeTicket = 100000
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Actif = false,
                            Adresse = "34 Quartier Sidi Moumen, Casablanca",
                            Code = "HAM006",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9124),
                            Nom = "Hammam Sidi Moumen",
                            NomArabe = "",
                            PrefixeTicket = 100000
                        });
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employe_id");

                    b.Property<Guid>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sync_status");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<Guid>("TypeTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeId");

                    b.HasIndex("HammamId");

                    b.HasIndex("TypeTicketId");

                    b.HasIndex("EmployeId", "CreatedAt");

                    b.HasIndex("HammamId", "CreatedAt");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.TypeTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("couleur");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User")
                        .HasColumnName("icone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.HasIndex("HammamId");

                    b.ToTable("type_ticket", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            Actif = true,
                            Couleur = "#3B82F6",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9263),
                            Icone = "User",
                            Nom = "HOMME",
                            Ordre = 1,
                            Prix = 15.00m
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2222-2222-2222-222222222222"),
                            Actif = true,
                            Couleur = "#EC4899",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9267),
                            Icone = "UserCheck",
                            Nom = "FEMME",
                            Ordre = 2,
                            Prix = 15.00m
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3333-3333-3333-333333333333"),
                            Actif = true,
                            Couleur = "#10B981",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9271),
                            Icone = "Baby",
                            Nom = "ENFANT",
                            Ordre = 3,
                            Prix = 10.00m
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4444-4444-4444-444444444444"),
                            Actif = true,
                            Couleur = "#06B6D4",
                            CreatedAt = new DateTime(2026, 2, 12, 17, 29, 50, 452, DateTimeKind.Utc).AddTicks(9273),
                            Icone = "Droplets",
                            Nom = "DOUCHE",
                            Ordre = 4,
                            Prix = 8.00m
                        });
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Versement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateVersement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_versement");

                    b.Property<decimal>("Ecart")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ecart");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employe_id");

                    b.Property<Guid>("HammamId")
                        .HasColumnType("uuid")
                        .HasColumnName("hammam_id");

                    b.Property<decimal>("MontantRemis")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montant_remis");

                    b.Property<decimal>("MontantTheorique")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montant_theorique");

                    b.Property<int>("NombreTickets")
                        .HasColumnType("integer")
                        .HasColumnName("nombre_tickets");

                    b.Property<Guid?>("ValidePar")
                        .HasColumnType("uuid")
                        .HasColumnName("valide_par");

                    b.HasKey("Id");

                    b.HasIndex("DateVersement");

                    b.HasIndex("EmployeId");

                    b.HasIndex("HammamId");

                    b.HasIndex("EmployeId", "DateVersement")
                        .IsUnique();

                    b.ToTable("versement", (string)null);
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Employe", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany("Employes")
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hammam");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Employe", "Employe")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany("Tickets")
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HammamAPI.Domain.Entities.TypeTicket", "TypeTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("TypeTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Hammam");

                    b.Navigation("TypeTicket");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.TypeTicket", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany("TypeTickets")
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Hammam");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Versement", b =>
                {
                    b.HasOne("HammamAPI.Domain.Entities.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HammamAPI.Domain.Entities.Hammam", "Hammam")
                        .WithMany()
                        .HasForeignKey("HammamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Hammam");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Employe", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.Hammam", b =>
                {
                    b.Navigation("Employes");

                    b.Navigation("Tickets");

                    b.Navigation("TypeTickets");
                });

            modelBuilder.Entity("HammamAPI.Domain.Entities.TypeTicket", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
